### PR TITLE
✨ Add prebidopenx as a vendor to RTC config

### PR DESCRIPTION
**Pull request by kenan-gillet**
* add prebidopenx as a vendor to RTC config
* add vendor to documentation pages

### CODE REVIEW

**Comment by kenan-gillet** [comment]
could you review before I make the official PR, thanks

**Review by mikeherrera1975 — APPROVED** [review]
LGTM.

**Review by laurb9 — APPROVED** [review]

**Comment by deivydas** [comment]
Hey @kenan-gillet 
it LGTM

**Review by deivydas — APPROVED** [review]
LGTM

**Review by luigi-sayson — APPROVED** [review]

**Pull request merged**
